highlighter: rouge
github: [Repository metadata]

baseurl: "http://kristenzirkler.github.io/hire-up-video"

# Sass
sass:
  sass_dir: scss
  style: :expanded
  line_numbers: true

# Gems
gems: ['jekyll-redirect-from']